apiVersion: batch/v1
kind: Job
metadata:
  name: stream
spec:
  parallelism: 20
  completions: 20
  template:
    metadata:
      name: stream-pod
    spec:
      containers:
      - name: stream-container
        image: benchmarks/centos-gcc-stream:latest
      nodeSelector:
        color: blue
      restartPolicy: Never
